### PR TITLE
revamp themes

### PR DESCRIPTION
**Pull request by IncognitoTGT**

### CODE REVIEW

**Review by Riftriot — CHANGES_REQUESTED** [review]
Please fix the credits page overflow on both the X and Y axis

**Comment by IncognitoTGT** [comment]
i suck at css bot ok

**Review by Riftriot — CHANGES_REQUESTED** [review]
Please remove the incredibly annoying flash on page load.

**Review by Riftriot — APPROVED** [review]
[Riftriot](https://github.com/Riftriot) requested changes [1 hour ago](https://github.com/NebulaServices/Nebula/pull/245#pullrequestreview-2002388558)

**Review by Riftriot — COMMENTED** [review]
This commit has been reverted. Please fix the particles being layered over the rest of the screen

**Comment by IncognitoTGT** [comment]
pov you rewrite the entire themes code:

**Pull request merged**
