### PR TITLE
Custom CSS, AB Customization, UV linking/config fix

### PR DESCRIPTION
**Pull request by Cattn**
Not sure if the AB Cloak is working 100%, so if someone could test it out would appreciate. (Probably won't break AB if not?)

I suggest whoever checks this will test the AB Feature beforehand. It should have no issue, but for the sake of it would probably be good to test. 

(Sorry for 3 commits lol had some issues)

### CODE REVIEW

**Comment by youngchief-btw** [comment]
LGTM! Ideally we get documentation alongside this soon, right?

**Comment by Cattn** [comment]
> LGTM! Ideally we get documentation alongside this soon, right?

Yep, The setup for custom themes is pretty specific and interactive, not just paste block of code. But I'll write some docs likely to show where the colors/elements go if names aren't clear enough

**Comment by Cattn** [comment]
yo @cohenerickson I think refactoring is done? I don't think this'll have issues, just could u take a look?

**Comment by cohenerickson** [comment]
It seems like the link isn't correctly being generated. When navigating to `example.com`, the iframe loads `/service/hvtr%3A-%2Fgxcmrlg.aoo` instead of `/service/go/hvtr%3A-%2Fgxcmrlg.aoo`.

**Review by 3kh0 — APPROVED** [review]
uses my system, so 3kh0 approved

**Comment by 3kh0** [comment]
I am referring to the cloak system

**Comment by Cattn** [comment]
> It seems like the link isn't correctly being generated. When navigating to `example.com`, the iframe loads `/service/hvtr%3A-%2Fgxcmrlg.aoo` instead of `/service/go/hvtr%3A-%2Fgxcmrlg.aoo`.
I think this was an issue before and not with my code, I'll take a look to see

**Comment by Cattn** [comment]
> uses my system, so 3kh0 approved

What's your system

**Comment by GreenyDEV** [comment]
All known bugs need to be fixes before changes are merged, please take a look at what Cohen mentioned.

**Comment by Cattn** [comment]
> All known bugs need to be fixes before changes are merged, please take a look at what Cohen mentioned.

Alright, will see what's going on here, seems to be unrelated my code, but I will take a crack at it

**Comment by GreenyDEV** [comment]
Also make sure the code you edited is the latest code!

**Comment by Cattn** [comment]
> Also make sure the code you edited is the latest code!

Yes, will do this time lmfao, Should be fine pulling from my branch

**Comment by Cattn** [comment]
Ok I think I've identified a fix, but I do not wish to break things, and also it doesn't make much sense.

https://github.com/Cattn/Nebula/blob/main/public/resources/nebulamain.js#L159 At this line, __uv$config.prefix seems to be returning /service/ instead of /service/go/ which I'm not sure why it is. Now maybe it's how I'm testing it locally? Idk for sure.

changing __uv$config.prefix + __uv$config.encodeUrl(url)

to __uv$config.prefix + 'go/' +  __uv$config.encodeUrl(url)
obv as a temp change fixed the issue for me that your describing

I think this issue is deeper than what I'm seeing

@cohenerickson

**Comment by Nailington** [comment]
After some slow cross-referencing, https://github.com/titaniumnetwork-dev/Ultraviolet/blob/main/src/uv.sw.js#L34 can be seen with `/service/` not `/service/go/`. Now why this matters is above my pay grade, as all I did was act like an idiot and accidentially found something possibly irrelevant.

**Comment by Cattn** [comment]
issue is it's setting the wrong prefix

@cohenerickson could you take care of this? this shouldn't be anything I've done as I didn't even touch how A:B loads

**Comment by Cattn** [comment]
https://github.com/NebulaServices/Nebula/pull/79/commits/36a41cd3ae8c1e145c1fb634d295722d85e29025 fixes it, but due to how config is setup the prefix is /service/ and not /service/go

I will be sleeping now

**Comment by Nailington** [comment]
> [36a41cd](https://github.com/NebulaServices/Nebula/commit/36a41cd3ae8c1e145c1fb634d295722d85e29025) fixes it, but due to how config is setup the prefix is /service/ and not /service/go
> 
> I will be sleeping now
> 
> `Yes, you were semi-right EV`

The only thing that confuses me rn is why explicitly @cohenerickson said to make it `/service/go/` when it is possible to get it to work otherwise... is there a reason why this was asked? Does the rest of Neb use the `/go`/ setup? And if you knew it SHOULD have had `/go/`, how did you know?

**Comment by Cattn** [comment]
I'm going to just revert my changes for now until Cohen looks at this thread

**Comment by GreenyDEV** [comment]
we're working on a fix for the service bug

**Comment by cohenerickson** [comment]
https://github.com/NebulaServices/Nebula/commit/990225e50ac708650f4db05396ca62fb040fd88d

This is not true, the official documentation for the ultraviolet library explicitly states that it can be done, I can fix this later today but not for a few more hours. It is simply just an issue with the order express is handling static routes.

**Comment by cohenerickson** [comment]
Please resolve conflicts with 059526d

**Comment by Cattn** [comment]
> Please resolve conflicts with [059526d](https://github.com/NebulaServices/Nebula/commit/059526d961f07c47ce1433c68fb3c45d8bd18bef)

Will do

**Review by cohenerickson — APPROVED** [review]

**Comment by Cattn** [comment]
Fixed, merging now!

**Pull request merged**
