### PR TITLE
AboutBlank Function abstraction; CSS fixes and improvements; iframeheader update, docker

### PR DESCRIPTION
**Pull request by IncognitoTGT**

### CODE REVIEW

**Review by Riftriot — CHANGES_REQUESTED** [review]
remove the useless changes

**Comment by IncognitoTGT** [comment]
they aren't useless
* docker
* I abstracted the aboutblank thing at last, fulfilling cohen's wishes
* searchbar moves up on small screens like mobile, and it's text shrinks on cumbooks, where it used to overflow
* hover color on catppuccin was broken so I fixed that
* fixed spacing in the misc tab
* and also color in the bare switcher card and search suggestions

**Comment by Riftriot** [comment]
image

**Comment by IncognitoTGT** [comment]
fixing brb

**Pull request closed without merging**
