### PR TITLE
aboutblank function unified; search bar moves up in small screens; Add Docker

### PR DESCRIPTION
**Pull request by IncognitoTGT**
* added License file
* about:blank opener is now also used for the button in the cloaking tab 
* the search bar moves up in small screens since it goes below the margin
* Added Dockerfile
* Fixed random css bugs

### CODE REVIEW

**Comment by IncognitoTGT** [comment]
pretty obvious

**Comment by wearrrrr** [comment]
You do realize that *you* don't choose the license right?

**Comment by IncognitoTGT** [comment]
I copied what was in the readme; didn't know it's old

**Comment by IncognitoTGT** [comment]
raaah stupid commit names
just see the files changed

**Comment by IncognitoTGT** [comment]
why merge conflict

**Comment by IncognitoTGT** [comment]
nvm how no conflict

**Comment by IncognitoTGT** [comment]
No I'm not changing the themes it's that hover was broken

**Review by Riftriot — CHANGES_REQUESTED** [review]
Please add tsx as an installed package for the dockerfile.

**Comment by IncognitoTGT** [comment]
It runs pnpm install which adds tax

**Comment by IncognitoTGT** [comment]
closing lmao

**Pull request closed without merging**
