### PR TITLE
Themes and css improvements

### PR DESCRIPTION
**Pull request by IncognitoTGT**
* Added Catppuccin Macchiato, and Frappe themes (Frappe bit iffy in settings page, fix tabs css there)
* Changed size of Eruda when it opens
* Changed Eruda's default theme
* Also fix typo in a filename (Catppuccin is hard to spell at first though)

FEgCb3T

### CODE REVIEW

**Comment by IncognitoTGT** [comment]
Added Latte theme and Schoology cloak
<@578375908247863296>

**Review by Riftriot — CHANGES_REQUESTED** [review]
Please remove the redundant **catppuccinText** utility class as the **input-text** class accomplishes the same thing.

**Review by Riftriot — CHANGES_REQUESTED** [review]
Please improve the settings icon contrast on Frappe. The icons are hardly visible.

**Comment by IncognitoTGT** [comment]
Fixed two

**Review by Riftriot — APPROVED** [review]
Tim sweeny would approve

**Pull request merged**
