### PR TITLE
Purge Cyclone

### PR DESCRIPTION
**Pull request by cohenerickson**
Purge any mention of Cyclone or System following the recent events.

The removal of Cyclone may also fix memory leak issues.

### CODE REVIEW

**Comment by illusionTBA** [comment]
seems fine 👍

**Comment by Snazzy-xyz** [comment]
> Purge any mention of Cyclone or System following the recent events.
> 
> The removal of Cyclone may also fix memory leak issues.

looks good to me

**Comment by wearrrrr** [comment]
Looks good to me

**Comment by GreenyDEV** [comment]
Looks good

**Pull request merged**
